Лекция 6, задача 3
IlyaOrlov/PythonCourseATIS_0422 pull request #12
Opened 2022-05-21 11:57 UTC by JackSlater777

2022-05-22 19:07 UTC, IlyaOrlov commented on Practice/karazanov/lec_6_2.py
> +def multiplier(m=1, source=None):
Решение верное. Еще можно было по умолчанию кортеж использовать, а итоговый результат представить, как return [x * m for x in source]. Но это если бы предполагалось, что переданный пользователем список не должен изменяться.

2022-05-22 19:20 UTC, IlyaOrlov requested changes
Всё отлично! Но есть существенное замечание и предложение!

2022-05-22 19:20 UTC, IlyaOrlov commented on Practice/karazanov/lec_6_4.py
> +from itertools import filterfalse
Понимаю, что здесь подразумевается разделение по заданиям, но всё-таки (раз уж весь код в одном файле) импорты и определения функция лучше вынести в начало файла. Комментарии можно оставить на месте.

2022-05-22 19:20 UTC, IlyaOrlov commented on Practice/karazanov/lec_6_4.py
> +    return list(res)
Здесь и далее в аналогичных случаях: один и тот же итератор (и генератор) можно пройти только один раз, затем надо создавать его заново. Попробуйте в стр. 22 сделать print(concatenate_lists(ls_x, ls_y, ls_z)) и посмотреть, что выведется.
Как вариант, можно сохранить результат list(res) в переменную и работать уже с этой переменной.

2022-05-23 17:02 UTC, JackSlater777 commented on Practice/karazanov/lec_6_4.py
> +from itertools import filterfalse
Поправил

2022-05-23 17:07 UTC, JackSlater777 commented on Practice/karazanov/lec_6_4.py
> +    return list(res)
При print(concatenate_lists(ls_x, ls_y, ls_z)) вывелся список [1, 2, 3, 4, 5, 6, 7]. Я не совсем понял проблематику, если честно...

2022-05-23 17:59 UTC, IlyaOrlov commented on Practice/karazanov/lec_6_4.py
> +    return list(res)
Т.е. вот для такого примера (с двумя принтами):
```python
from itertools import chain


def concatenate_lists(x, y, z):
    res = chain(x, y, z)
    print(list(res))
    return list(res)


ls_x = [1, 2, 3]
ls_y = [4, 5]
ls_z = [6, 7]
print(concatenate_lists(ls_x, ls_y, ls_z))
```
у Вас два раза вывелся список [1, 2, 3, 4, 5, 6, 7]?

2022-05-23 18:11 UTC, JackSlater777 commented on Practice/karazanov/lec_6_4.py
> +    return list(res)
Аа, теперь понял. Я закомментировал принт внутри функции. Поправил, ввёл переменную под список

2022-05-23 18:26 UTC, IlyaOrlov commented on Practice/karazanov/lec_6_4.py
> +    return list(res)
Отлично! Но проблема актуальна и для других итераторов в этом файле!
Также код стоит немного сократить, избавившись, например, от промежуточной переменной res.

2022-05-23 18:32 UTC, JackSlater777 commented on Practice/karazanov/lec_6_4.py
> +    return list(res)
Сделано

2022-05-23 18:34 UTC, merged