Новые задачи (из 7 лекции и экзамена)
IlyaOrlov/PythonCourseATIS_0422 pull request #13
Opened 2022-05-24 18:11 UTC by JackSlater777

2022-05-24 19:39 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_2.py
> +def calc_work_days(fst, sec):
Отлично! Но надо учесть и выходные дни.

2022-05-29 09:51 UTC, JackSlater777 commented on Practice/karazanov/lec_7_2.py
> +def calc_work_days(fst, sec):
Сделано

2022-05-29 14:18 UTC, JackSlater777 commented
В дополнение к задаче 3 из 7 лекции.
Если я пробую вывести свойства экземпляра через метод options вот так:

for human in humans_lst:
    example_fabric(human)
    human.options()

то получаю ошибку:
AttributeError: 'function' object has no attribute 'options'

Не понимаю, почему так происходит.

2022-05-29 20:18 UTC, IlyaOrlov requested changes
Есть существенные замечания!

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/Another practice/test1.py
> +        r = open(dest, 'x')
Почему бы к dest тоже не применить with?

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1.py
> +with open(r'C:\Users\Иван\Desktop\python_work\PythonCourseATIS_0422\Practice\README.md') as f:
Здесь и в других случаях лучше относительный путь. И лучше вывести его в отдельную переменную.

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +with open(r'C:\Users\Иван\Desktop\python_work\PythonCourseATIS_0422\Practice\karazanov\text.txt') as f:
Лучше относительный путь. И его надо вынести в отдельную переменную.

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +    s = f.read()  # Переносим текст файла в переменную
Здесь мы сразу всё считываем из файла, и смысл итератора теряется. Можно считывать посимвольно: read(1). И итератор - это класс.

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_2_pretask.py
> +    s = f.read()  # Переносим текст файла в переменную
И здесь мы опять считываем сразу всё содержимое файла. Лучше передать в генератор только путь, а открытие, чтение и т.д. он пусть сделает сам.

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_3.py
> +humans_lst = [Human.__init__ for _ in range(n)]
Мы создаем n ссылок на метод ```___init___```... Зачем? Здесь-то как раз и надо example_fabric вызывать.
Явное обращение к ```___init___``` уже должно наводить на мысль, что тут что-то не так.

2022-05-29 20:18 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_3.py
> +def example_fabric(hum):
Зачем сюда передавать hum? Мы же его здесь как раз и должны создавать. Если с 27-й по 42 убрать hum, то всё будет ОК.

2022-05-29 20:19 UTC, IlyaOrlov commented
> В дополнение к задаче 3 из 7 лекции. Если я пробую вывести свойства экземпляра через метод options вот так:
> 
> for human in humans_lst: example_fabric(human) human.options()
> 
> то получаю ошибку: AttributeError: 'function' object has no attribute 'options'
> 
> Не понимаю, почему так происходит.

Потому что human - это функция. Конкретно, метод ```Human.__init__```.

2022-05-30 18:17 UTC, JackSlater777 commented on Practice/karazanov/Abstract/libraries.py
> +for i in os.listdir('..'):  # Количество точек - количество уровней выше, откуда будет браться инфо
Исправлю

2022-05-30 18:18 UTC, JackSlater777 commented on Practice/karazanov/Another practice/test1.py
> +        r = open(dest, 'x')
Это тестовый файл с сырым кодом, но в файле Exam я так не сделал) Продублируйте, пожалуйста, если не забудете

2022-05-30 18:27 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1.py
> +with open(r'C:\Users\Иван\Desktop\python_work\PythonCourseATIS_0422\Practice\README.md') as f:
Исправлено

2022-05-30 18:29 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1_pretask.py
> +with open(r'C:\Users\Иван\Desktop\python_work\PythonCourseATIS_0422\Practice\karazanov\text.txt') as f:
Сделано

2022-05-30 18:30 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1_pretask.py
> +    s = f.read()  # Переносим текст файла в переменную
Переделаю

2022-05-30 18:50 UTC, JackSlater777 commented on Practice/karazanov/lec_7_3.py
> +humans_lst = [Human.__init__ for _ in range(n)]
Переделаю

2022-05-31 09:49 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +    try:
Начать стоит с проверки s - файл это или папка (есть функции os.path.isdir и os.path.isfile). Если файл - то - copyfile, если папка - то создаем одноименную папку и рекурсивно применяем copydir.

2022-05-31 09:50 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +import re
Здесь всё ОК.

2022-05-31 09:54 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_2_pretask.py
> +        s = f.read()  # Переносим текст файла в переменную
И опять мы здесь ВЕСЬ файл сразу считываем. А надо построчно! Объект f уже является итератором, а значит, по нему можно идти циклом for.

2022-05-31 09:54 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_2_pretask.py
> +    s = f.read()  # Переносим текст файла в переменную
Подсказал)

2022-05-31 16:44 UTC, JackSlater777 commented on Practice/karazanov/Another practice/test1.py
> +        r = open(dest, 'x')
Да, я завёл эту папку, чтобы всё рядом было

2022-05-31 17:28 UTC, JackSlater777 commented on Practice/karazanov/lec_7_3.py
> +humans_lst = [Human.__init__ for _ in range(n)]
Исправлено

2022-05-31 17:28 UTC, JackSlater777 commented on Practice/karazanov/lec_7_3.py
> +def example_fabric(hum):
Исправлено

2022-05-31 17:50 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        g = open(dest, 'x')  # Открываем destination - если не существует, выбрасывает исключение
Поправил. Файл залью позже, когда замечания по остальным задачам исправлю

2022-06-01 03:53 UTC, JackSlater777 commented
> Замечания ещё остаются... Надо всё-таки договориться, какие файлы мне проверять не нужно. Кстати, можно указать папку, которую вы не планируете отправлять в гитхаб, прописать в файл .gitignore, тогда гит будет игнорировать файлы из этой папки.

Сделал файл гитигнор на две папки: Abstract и Another Practice.

2022-06-01 17:36 UTC, JackSlater777 commented on Practice/karazanov/lec_7_3.py
> +my_deserialization(path)
Сделано

2022-06-03 10:42 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +def my_range(*args):
стр.47-48 и 51-52 одинаковые, можно вынести этот код под общее условие elif len(args) > 1

2022-06-03 11:05 UTC, IlyaOrlov requested changes
Ещё есть существенные замечания!

2022-06-03 11:05 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +my_sum1.__add__(my_sum2)
Только явно этот метод (и все методы ниже) вызывать не надо. Просто: print(my_sum1 + my_sum2)

2022-06-03 11:05 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +        print(f"Сумма в рублях: {summ}")
Принты в таких методах будут неприятным сюрпризом для пользователя Money. Он захочет поcчитать res = money1 + money2 + money3, а у него помимо итогового результата выведется еще и результат сложения money1 + money2.

2022-06-03 13:57 UTC, JackSlater777 commented on Practice/karazanov/lec_7_2_pretask.py
> +next(g)
Поправил

2022-06-03 14:04 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        for file in files:
А подпапки тоже надо копировать или их пропускать?

2022-06-03 14:25 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        print(f"Сумма в рублях: {summ}")
Я думал, что self и other применимы только для операций с атрибутами двух экземпляров. Как быть, если надо произвести операцию с тремя?

2022-06-03 14:35 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +my_sum1.__add__(my_sum2)
Поправил

2022-06-03 18:26 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1_pretask.py
> +    for i in MyIter(f, '\n', s):
Когда я так делаю, он выдает: ValueError: I/O operation on closed file.

2022-06-04 07:49 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +        for file in files:
Желательно копировать. Ну и цикл for здесь подходит, и да, рекурсия тоже.

2022-06-04 07:56 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +        print(f"Сумма в рублях: {summ}")
Достаточно сказать интерпретатору, как осуществлять эту операцию с двумя экземплярами так, чтоб результатом был тоже экземпляр этого класса. Потому что money1 + money2 + money3 = (money1 + money2) + money3: из money1 + money2 получается некий новый экземпляр money, и затем интерпретатору остается сложить money + money3 (т.е. задача в любом случае сводится к суммированию двух слагаемых класса Money).
Если бы результатом money1 + money2 было число, например, 100, то следующим шагом интерпретатору пришлось бы складывать 100 + money3, а этому мы его не учили.

2022-06-04 07:58 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +my_sum1.__add__(my_sum2)
Не вижу исправления.

2022-06-04 07:58 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +        return summ
Не вижу изменений.

2022-06-04 08:02 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +    for i in MyIter(f, '\n', s):
Только with здесь уже использовать не получится. Иначе там же, где вы его откроете, он и закроется. В ```___init__``` должен быть просто self._f = open(path). А вот close() можно поместить непосредственно перед raise StopIteration.

2022-06-04 08:05 UTC, IlyaOrlov requested changes
По некоторым замечаниям написано "Сделано", но изменений не видно. Похоже, исправления до гитхаба не доехали.

2022-06-04 08:05 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +def my_range(*args):
Не вижу изменений.

2022-06-04 19:08 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +my_sum1.__add__(my_sum2)
Файл не выслал, потому что сначала хотел исправить все ошибки :) Выслал. В 8 еще без рекурсии и в 10 задаче для 3 экземпляров не работает.

2022-06-05 09:18 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1_pretask.py
> +    for i in MyIter(f, '\n', s):
Сделано

2022-06-05 10:35 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +my_sum1.__add__(my_sum2)
Дорешал восьмую

2022-06-05 18:26 UTC, IlyaOrlov requested changes
Остаются существенные замечания по Exam и итератору.

2022-06-05 18:26 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +    if not os.path.exists(d) and cnt == 0:
Учитывая, что при копировании подпапок мы их создаем уровнем выше, здесь должно быть достаточно проверки ```if not os.path.exists(d)```.  И можно ```os.mkdir(fl_copy)``` из строки 225 убрать (копии подпапок будут создаваться здесь, а не уровнем выше).
А то вариант с cnt выглядит сложновато.

2022-06-05 18:26 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +        for arg in args:
compare не надо создавать отдельно. Если магические методы не вызывались не разу, compare просто создан зря. Если методы вызываются, а compare создать забыли - будет ошибка. В общем случае зависимость функции/методов от глобальных переменных - плохое решение. Новый экземпляр должен создаваться прямо здесь:
```python
 def __add__(self, other):
    rub = self.ruble + other.ruble
    kop = self.kopeyka + other.kopeyka
    exchange = self.exchange  # тут решение неоднозначное и остается на усмотрение разработчика
    return Money(rub, kop, exchange)
```
Аналогично и для ```__sub__```.
Для ```__truediv__``` всё не так однозначно. Надо подумать над вопросом, что должно получиться при делении денег на деньги, исходя из того, где это может использоваться? Например, на сколько человек можно поделить 1000р., чтоб каждому досталось по 100р.? В этом случае ответом, очевидно, будет количество человек (т.е. просто число) - 10. 
compare в любом случае использовать не следует.

2022-06-05 18:26 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +        self._buffer = ''
buffer хранить не надо, он будет заполняться внутри ```__next__```, возвращаться и затем заполняться заново следующим параграфом.

2022-06-05 18:26 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +        buffer = self._buffer
buffer = ''

2022-06-05 18:26 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +                elif self._s == self._t:
Здесь тогда просто else, т.к. они либо равны, либо не равны.

2022-06-05 18:26 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +        for j in self._f:
Вместо строк 18 и 19: ```while self._s:``` и в конец тела цикла добавьте снова ```self._s = self._f.read(1)``` - будет хорошо)
Сейчас, если символ параграфа отличается от символа переноса строки (например, \t), мы можем потерять всё, что в строке с символом параграфа идёт после этого символа. Например, в тексте "Когда я, наконец, прочитаю \t этот текст" - мы потеряем " этот текст".

2022-06-06 18:18 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +    if 3 < len(args) < 1:
Сделал через or

2022-06-06 18:25 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        for arg in args:
Переделал сложение и вычитание. Остался вопрос, как вывести получившуюся информацию (вместо object вывести сумму или разницу). Деление не трогал, концепт не до конца понял. Compare убрал.

2022-06-06 18:25 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1_pretask.py
> +        buffer = self._buffer
Переделал

2022-06-07 10:05 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +    if not os.path.exists(d) and cnt == 0:
Подпапка создастся в той папке, которую вы передали на место d. Надо правильно формировать пути:
fl = os.path.join(s, file)
fl_copy = os.path.join(d, file)
Это независимо от того, является ли file папкой или файлом.

2022-06-07 10:12 UTC, IlyaOrlov commented on Practice/karazanov/lec_7_1_pretask.py
> +        self._buffer = ''
Отлично! И ещё последний штрих: вызов self._f.close() стоит ещё добавить в магический метод ```__del__``` (это деструктор, который автоматически вызывается, когда счетчик ссылок объекта становится равным нулю). Тогда если вдруг не сработала строка 22 (если перед этим исключение случилось, или мы просто недовызывали next до конца текста), файл всё равно закроется вместе с удалением экземпляра MyIter().

2022-06-07 10:16 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +    if 3 < len(args) < 1:
Потому что в исходном варианте оно всегда будет возвращать False: длина списка не может одновременно быть больше 3-х и меньше 1-го. 
3 < len(args) < 1 это то же самое, что 3 < len(args) **and** len(args) < 1, а не 3 < len(args) **or** len(args) < 1, как могло показаться.

2022-06-07 15:03 UTC, JackSlater777 commented on Practice/karazanov/lec_7_1_pretask.py
> +        self._buffer = ''
Выполнено.

2022-06-07 17:46 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +    if not os.path.exists(d) and cnt == 0:
Да, сработало. Обновил.

2022-06-07 18:09 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        for arg in args:
Прописал метод репр, но неправильно. Подскажите, как стоит в данном случае его прописывать

2022-06-07 18:32 UTC, IlyaOrlov commented on Practice/karazanov/Exam.py
> +        for arg in args:
репр должен **возвращать** строку!

2022-06-08 03:47 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        print(f"{self.ruble_sum=}")
Про самое простое забыл :) Поправил

2022-06-08 03:48 UTC, JackSlater777 commented on Practice/karazanov/Exam.py
> +        for arg in args:
Поправил

2022-06-08 07:23 UTC, IlyaOrlov approved these changes
Pull Request я замержу (т.к. он уже сильно разросся), но lec_8_1.py и lec_8_2.py надо будет поправить/доделать.

2022-06-08 07:23 UTC, merged