maxXY.py
IlyaOrlov/PythonCourseATIS_0422 pull request #4
Opened 2022-04-12 17:43 UTC by K2D4E

2022-04-13 14:58 UTC, IlyaOrlov requested changes
Оставил некоторые замечания. Если что-то в замечаниях непонятно, или вызывает вопросы - пишите прямо ответом на эти замечания, что нужно расписать или объяснить подробнее.

2022-04-13 14:58 UTC, IlyaOrlov commented on Practice/KDE/pep8task.py
> +import sys
Здесь нужны комментарии к тем строкам, в которых вы обнаружили ошибки, о том, в чем ошибка.

2022-04-20 09:01 UTC, IlyaOrlov requested changes
Всё хорошо. Но есть еще замечания (преимущественно, по стилю). Если будут трудности с английским (при чтении документа PEP8), можно воспользоваться гугл-переводчиком (смысл сохранится).

2022-04-23 08:09 UTC, IlyaOrlov requested changes
Всё хорошо. Оставил несколько небольших замечаний.

2022-04-23 08:09 UTC, IlyaOrlov commented on Practice/KDE/pep8task.py
> +            f = open(output, 'r')
Определенно здесь есть ошибка со смещением, но...
В строках 24-25 выполняется открытие файла output и запись в него self.map.
self.map это некий контейнер, который заполняется строками внутри цикла for.
Сдвиг этих строк вправо (внутрь цикла for) приведет к тому, что каждый раз, когда мы что-то добавили в self.map, мы будем перезаписывать его в файл.
В случае же сдвига влево (вне цикла for) мы запишем в файл только один раз итоговое содержимое self.map.
Циклы и файлы мы ещё пройдем, но хотелось бы уже сейчас обратить ваше внимание на то, как выравнивание кода влияет на весь алгоритм вычислений.

2022-04-25 11:01 UTC, IlyaOrlov requested changes
Класс и примеры получись отличные. Есть только некоторые замечания по стилю.

2022-04-25 11:01 UTC, IlyaOrlov commented on Practice/KDE/classtest1.py
> +    def __init__(self, name, speed, xp, xp_shoot, col_shoot):  # конструктор init для добовления информации о
Комментарий (особенно, если он не помешается в одну строку) лучше написать перед кодом, к которому он относится.
При этом, комментировать конструктор особого смысла нет, т.к. он по определению всегда используется для добавления информации об экземпляре класса.

2022-04-25 20:36 UTC, K2D4E commented on Practice/KDE/classtest1.py
> +                f'Name: {self.name}, speed: {self.speed}, Xp: {self.xp},xp_shoot: {self.xp_shoot},col_shoot: {self.col_shoot}')
пытался перевести через '\' в принте идет больше смещение не знаю как решить , хотел обсудить на лекции

2022-04-25 20:38 UTC, K2D4E commented on Practice/KDE/classtest1.py
> +                f'Name: {self.name}, speed: {self.speed}, Xp: {self.xp},xp_shoot: {self.xp_shoot},col_shoot: {self.col_shoot}')
через слеш

2022-04-26 07:28 UTC, IlyaOrlov commented on Practice/KDE/classtest1.py
> +                f'Name: {self.name}, speed: {self.speed}, Xp: {self.xp},xp_shoot: {self.xp_shoot},col_shoot: {self.col_shoot}')
Можно и через слеш. А можно так (PyCharm сам такое выравнивание предлагает):
```python
            print(f'Name: {self.name}, speed: {self.speed}, Xp: {self.xp}, '
                  f'xp_shoot: {self.xp_shoot},col_shoot: {self.col_shoot}')
```
Да, это тоже всё в одну строку выведется.

2022-04-26 07:31 UTC, IlyaOrlov requested changes
Всё ОК. Осталось решить с переносом аргумента print.

2022-04-26 15:26 UTC, IlyaOrlov approved these changes

2022-04-26 15:26 UTC, merged