comments on pep8
IlyaOrlov/PythonCourseATIS_0422 pull request #5
Opened 2022-04-18 09:21 UTC by OksanaZh1

2022-04-18 09:26 UTC, IlyaOrlov requested changes
Хорошо, но по некоторым строкам требуются уточнения.

2022-04-18 09:26 UTC, IlyaOrlov commented on Practice/ozharova/pep8_oks.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname)) # ошибка со скобками
А что именно не так со скобками (здесь и в стр. 36)?

2022-04-18 09:26 UTC, IlyaOrlov commented on Practice/ozharova/pep8_oks.py
> +from time import *
Обратите также внимание на эту строку.

2022-04-18 13:32 UTC, IlyaOrlov requested changes
Всё супер! Оставил только небольшие замечания по стилю.

2022-04-18 13:32 UTC, IlyaOrlov commented on Practice/ozharova/lec2_max.py
> +def maximum(x,y):
Как следует из данного примера ([PEP8](https://peps.python.org/pep-0008/#:~:text=Immediately%20before%20a%20comma%2C%20semicolon%2C%20or%20colon%3A)), после запятой в списке аргументов функции или любого другого перечисления стоит поставить пробел после запятой.
То же самое в строках 8, 18 и 20.

2022-04-19 11:04 UTC, IlyaOrlov requested changes
Всё ОК. Ещё пара исправлений осталась.

2022-04-19 11:04 UTC, IlyaOrlov commented on Practice/ozharova/pep8_oks.py
> +from time import *
Да, вы правы, этот момент я еще не рассказывал) В двух словах: "from time import *" - это импорт всего содержимого (без разбору) из библиотеки time. Это нехорошо, т.к. может возникнуть путаница в именах переменных из импортируемого файла и текущего. Лучше просто import time.
Но мы эту проблему еще обсудим подробно.

2022-04-20 13:57 UTC, OksanaZh1 commented on Practice/ozharova/pep8_oks.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname)) # впереди пропущена открывающая скобка, одна лишняя последняя
Исправлено

2022-04-20 13:58 UTC, OksanaZh1 commented on Practice/ozharova/pep8_oks.py
> +from time import *
Исправлено

2022-04-20 18:29 UTC, OksanaZh1 commented on Practice/ozharova/pep8_oks.py
> +            os.rename(path + '/' + hashname, path + '/' + self.map[hashname])) # первая и вторая закрывающие скобки лишние
Исправлено

2022-04-20 18:48 UTC, IlyaOrlov approved these changes
Теперь совсем всё отлично)

2022-04-20 18:48 UTC, merged